# Generated by Django 3.2 on 2021-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_commentlike_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_post',
            field=models.TextField(max_length=10000, verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=264, verbose_name='Blog Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='blog_images', verbose_name='Image'),
        ),
    ]
